[workspace]
resolver = "2"
members = ["bin/*", "packages/*"]

[workspace.dependencies]
protocol = {path = "packages/protocol", version = "0.1.0"}
tokio = "1.44.1"
bincode = "1.2.1"
tokio-util = "0.6.0"
bytes = "1.10.1"
serde = "1.0.219"
futures = "0.3.31"
prost = "0.13.5"

