
[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
calproto_rust = {workspace = true}
stdin_kb = {workspace = true}
tokio = { workspace = true, features = ["full"] }
protocol = {workspace = true}